version: "3.5"

x-project-mount:
  &project-mount
  type: bind
  source: ./repository

services:
  monitor:
    image: ethereum/source-verify:monitor-${TAG}
    env_file:
    - .env.${TAG}
    container_name: monitor
    build:
      context: .
      dockerfile: src/Dockerfile.monitor
    ports:
    - "${MONITOR_EXTERNAL_PORT}:${MONITOR_PORT}"
    restart: always
    volumes:
      - <<: *project-mount
        target: /app/repository
  ui:
    image: ethereum/source-verify:ui-${TAG}
    env_file:
    - .env.${TAG}
    container_name: ui
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
    - "${UI_EXTERNAL_PORT}:${UI_PORT}"
    restart: always
    volumes:
    - ./.env.${TAG}:/app/.env
  server:
    image: ethereum/source-verify:server-${TAG}
    env_file:
    - .env.${TAG}
    container_name: server
    build:
      context: .
      dockerfile: src/Dockerfile.server
    ports:
    - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
    volumes:
      - <<: *project-mount
        target: /app/repository
    restart: always
  localchain:
    image: ethereum/source-verify:localchain-${TAG}
    env_file:
    - .env.${TAG}
    container_name: localchain
    build:
      context: .
      dockerfile: src/Dockerfile.localchain
    ports:
    - "${LOCALCHAIN_EXTERNAL_PORT}:${LOCALCHAIN_PORT}"
    restart: always
  repository:
    image: ethereum/source-verify:repository-${TAG}
    build:
      context: h5ai-nginx
      dockerfile: Dockerfile
    restart: always
    container_name: repository
    volumes:
      - h5ai:/h5ai
      - <<: *project-mount
        target: /data     
      - ./h5ai-nginx/options.json:/h5ai/_h5ai/private/conf/options.json
      - ./h5ai-nginx/types.json:/h5ai/_h5ai/private/conf/types.json
    ports:
    - ${REPOSITORY_EXTERNAL_PORT}:${REPOSITORY_PORT}
  s3sync:
    image: ethereum/source-verify:s3-${TAG}
    container_name: s3sync
    build:
      context: .
      dockerfile: Dockerfile.s3
    restart: always
    volumes:
      - <<: *project-mount
        target: /app/repository
volumes:
  repository:
  db:
  h5ai:
    driver: local
