version: "3.7"
x-project-repository-mount:
  &project-repository-mount
  type: bind
  source: ../repository
  
x-project-base:
  &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

networks:
  source-verify:
  
services:
  s3sync:
    <<: *project-base
    image: ethereum/source-verify:ipfs-${TAG}
    container_name: ipfs-${TAG}
    volumes:
      - <<: *project-repository-mount
        target: /app/repository
